apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-flask-app-deployment
  labels:
    app: todo-flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-flask-app
  template:
    metadata:
      labels:
        app: todo-flask-app
    spec:
      containers:
      - name: todo-app
        image: shahrukhjamadar/todo-flask:latest
        ports:
        - containerPort: 80



---




apiVersion: v1
kind: Service
metadata:
  name: todo-flask-app-service
spec:
  type: NodePort
  selector:
    app: todo-flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30009


